server:
  port: 8004
  
spring:
  servlet:
    multipart:
      max-file-size: 100Mb
      maxRequestSize: 1000Mb
      
datasource:
  mysql:
    JdbcUrl: jdbc:mysql://127.0.0.1:3306/filemgr?useUnicode=true&characterEncoding=utf8&useSSL=false
    DriverClassName: com.mysql.jdbc.Driver
    Username: root
    Password: 123456
    useSSL: false
 